PassionProject/Models/Application.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace PassionProject.Models
{
    public class Application
    {
        [Key, ScaffoldColumn(false)]
        public int ApplicationId { get; set; }


        // Application Date 
        // got this code from stackoverflow
        // it helps me declare a date data type
        // date accessed: feb 2 2019
        // author: Ladislav Mrnka
        // source: https://stackoverflow.com/questions/5658216/entity-framework-code-first-date-field-creation

        [Column(TypeName = "Date")]
        public DateTime ApplicationDate { get; set; }

        public virtual ICollection<Guild> Guild { get; set; }
        public virtual ICollection<Player> Player { get; set; }

    }
}

PassionProject/Models/Category.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class Category
    {
        [Key, ScaffoldColumn(false)]
        public int CategoryID { get; set; }

        [Required, StringLength(255), Display(Name = "Category Name")]
        public string CategoryName { get; set; }

        [StringLength(255), Display(Name = "Description")]
        public string CategoryDescription { get; set; }

        public virtual ICollection<Game> Games { get; set; }
    }
}

PassionProject/Models/Game.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class Game
    {
        [Key, ScaffoldColumn(false)]
        public int GameID { get; set; }

        [Required, StringLength(255), Display(Name = "Game Name")]
        public string GameName { get; set; }

        [StringLength(255), Display(Name = "Description")]
        public string GameDescription { get; set; }

        public int HasLogo { get; set; }

        [StringLength(255), Display(Name = "Game Logo")]
        public string GameLogo { get; set; }

        public virtual ICollection<Category> Categories { get; set; }
    }
}

PassionProject/Models/Guild.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class Guild
    {
        [Key, ScaffoldColumn(false)]
        public int GuildId { get; set; }

        [Required, StringLength(255), Display(Name = "Guild Name")]
        public string GuildName { get; set; }

        [StringLength(255), Display(Name = "Description")]
        public string GuildDescription { get; set; }

        public int HasEmblem { get; set; }

        [StringLength(255), Display(Name = "Guild Emblem")]
        public string GuildEmblem{ get; set; }

        public virtual Game game { get; set; }
        public virtual ICollection<Application> Application { get; set; }
    }
}

PassionProject/Models/Player.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class Player
    {
        [Key, ScaffoldColumn(false)]
        public int PlayerID { get; set; }

        [Required, StringLength(255), Display(Name = "First Name")]
        public string PlayerFName { get; set; }

        [Required, StringLength(255), Display(Name = "Last Name")]
        public string PlayerLName { get; set; }

        [StringLength(255), Display(Name = "Discord Tag Name")]
        public string PlayerDiscord { get; set; }

        public int HasAvatar { get; set; }

        [StringLength(255), Display(Name = "Avatar")]
        public string PlayerAvatar { get; set; }

        public virtual ICollection<Game> Games { get; set; }

        // To Do : create a friendship Module
        // public virtual ICollection<Friendship> Friends { get; set; }
    }
}

PassionProject/Models/TeamBuilderContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace PassionProject.Models
{
    public class TeamBuilderContext : DbContext
    {
        public TeamBuilderContext()
        {

        }

        public DbSet<Player> Players { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<Guild> Guilds { get; set; }
        public DbSet<Game> Games { get; set; }
    }
}

PassionProject/Controllers/ApplicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class ApplicationController : Controller
    {
        // GET: Application
        public ActionResult Index()
        {
            return View();
        }
    }
}

PassionProject/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
    }
}

PassionProject/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class GameController : Controller
    {
        // GET: Game
        public ActionResult Index()
        {
            return View();
        }
    }
}

PassionProject/Controllers/GuildController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class GuildController : Controller
    {
        // GET: Guild
        public ActionResult Index()
        {
            return View();
        }
    }
}

PassionProject/Controllers/HomeController.cs
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PassionProject/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.Data.Sql;
using PassionProject.Models;
using System.Diagnostics;
using System.Data.SqlClient;

namespace PassionProject.Controllers
{
    public class PlayerController : Controller
    {
        private TeamBuilderContext database = new TeamBuilderContext();
        public ActionResult Index()
        {
            return RedirectToAction("PlayerList");
        }

        public ActionResult PlayerList()
        {
            return View(database.Players.ToList());
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult PlayerProfile(int id)
        {
            string query = "select * from players where playerid = @id";
            Debug.WriteLine(query);
            return View(database.Players.SqlQuery(query, new SqlParameter("@id", id)).FirstOrDefault());
        }

        // Register an Account
        [HttpPost]
        public ActionResult NewPlayer(string PlayerFName_New, string PlayerLName_New, string PlayerDiscord_New)
        {
            return View();
        }



    }
}

PassionProject/Views/Guild/Create.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PassionProject/Views/Guild/Delete.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PassionProject/Views/Guild/Edit.cshtml
@model PassionProject.Models.Player

@{
    ViewBag.Title = "Edit Player";
}
<h2>Register a New Player</h2>
@using (Html.BeginForm("Edit", "Author", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="col-md-12">
        <div class="cole-md-6 col-md-offset-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <form>
            <fieldset>
                <legend>
                    Player Details
                </legend>
                @Html.HiddenFor(model => model.PlayerID)
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerFName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerFName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PlayerFName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerLName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerLName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PlayerLName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerDiscord, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerDiscord, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <legend>Upload an avatar</legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerAvatar, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        <div class="input-group mb-3">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="avatarUpload">
                                <label class="custom-file-label" for="avatarUpload">Choose file</label>
                            </div>
                            <div class="input-group-append">
                                <span class="input-group-text" id="">Upload</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Update" class="btn btn-default" />
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
}

PassionProject/Views/Guild/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PassionProject/Views/Guild/Profile.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PassionProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

PassionProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

PassionProject/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

PassionProject/Views/Player/Delete.cshtml
@model PassionProject.Models.Player

@{
    ViewBag.Title = "Delete Player";
}
<div class="col-md-8 col-md-offset-4">
    <h2>Delete player</h2>
    <div class="media">
        <img src="~/img/players/@Html.DisplayFor(model=>model.PlayerAvatar)" class="mr-3" alt="...">
        <div class="media-body">
            <h5 class="mt-0">@Html.DisplayFor(model => model.PlayerFName) @Html.DisplayFor(model => model.PlayerLName)</h5>
            <p>Discord Tag: @Html.DisplayFor(model => model.PlayerDiscord)</p>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Cancel", "Index")
                </div>
            }
        </div>
    </div>
</div>

PassionProject/Views/Player/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

PassionProject/Views/Player/PlayerList.cshtml
@model IEnumerable<PassionProject.Models.Player>

@{
    ViewBag.Title = "Players";
}
<div class="banner" id="authorbanner">
    <h2>Authors</h2>
</div>
<div class="recadd">
    @Html.ActionLink("Register an Account", "Register")
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PlayerAvatar)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerFName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerLName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PlayerDiscord)
        </th>
        <th></th>
    </tr>

    @foreach (var players in Model)
    {
        <tr>
            <td>
                <img src="@Html.DisplayFor(modelItem => players.PlayerAvatar)" class="rounded" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => players.PlayerFName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => players.PlayerLName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => players.PlayerDiscord)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = players.PlayerID }) |
                @Html.ActionLink("View Profile", "Profile", new { id = players.PlayerID }) |
                @Html.ActionLink("Delete", "Delete", new { id = players.PlayerID })
            </td>
        </tr>
    }

</table>

PassionProject/Views/Player/PlayerProfile.cshtml
@model PassionProject.Models.Player

@{
    ViewBag.Title = "Profile";
}
<div class="promptlink">
    @Html.ActionLink("Edit Profile", "Edit", new { id = Model.PlayerID })
</div>
<div class="promptlinkleft">
    @Html.ActionLink("Back to Players List", "Index")
</div>
<div>
    <div class="col-md-6 col-md-offset-6">
        <div class="img-container">
            @if (Model.HasAvatar == 1)
            {

                <div class="img-container">
                    <img src="~/imgs/authors/@Model.PlayerAvatar" />
                </div>
            }
            else
            {
                <img src="~/imgs/authors/default.jpg" />
            }
        </div>
        <h2>@Model.PlayerFName  @Model.PlayerLName</h2>
        <p> Discord Tag: @Model.PlayerDiscord </p>
    </div>
    <h4>Games Played by @Model.PlayerFName  @Model.PlayerLName</h4>
    <div class="gameList">
        @foreach (var game in Model.Games)
        {
            <div class="media">
                <img src="~/img/games/@game.GameLogo" class="mr-3" alt="...">
                <div class="media-body">
                    <h5 class="mt-0">@game.GameName</h5>
                    <p>@game.GameDescription</p>
                    @Html.ActionLink(game.GameName, "View/" + game.GameID, "Game")
                </div>
            </div>
        }
    </div>
</div>

PassionProject/Views/Player/Register.cshtml
@model PassionProject.Models.Player

@{
    ViewBag.Title = "Register A New Player";
}
<h2>Register a New Player</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="col-md-12">
        <div class="cole-md-6 col-md-offset-6">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <form>
            <fieldset>
                <legend>
                    Player Details
                </legend>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerFName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerFName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PlayerFName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerLName, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerLName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PlayerLName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.PlayerDiscord, htmlAttributes: new { @class = "control-label col-md-4" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.PlayerDiscord, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-8">
                        <input type="submit" value="Register" class="btn btn-default" />
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
}

PassionProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>